"""inicial: tabela insights

Revision ID: 5ef5fda8e15a
Revises: 
Create Date: 2026-10-06 10:16:52.959583

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Identificadores usados pelo Alembic para encadear as migrações.
revision: str = '5ef5fda8e15a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('secao', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('segmento', sa.String(length=100), nullable=True),
    sa.Column('servico', sa.String(length=100), nullable=True),
    sa.Column('o_que_foi_feito', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.Integer(), nullable=False),
    sa.Column('contexto_cliente', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=True),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('fonte_ref', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('motivo_obsolescencia', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insights')
    # ### end Alembic commands ###
