"""relacoes, historico de status e indices

Revision ID: 24ab6255ddc0
Revises: 5ef5fda8e15a
Create Date: 2026-10-06 10:24:01.358458

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Identificadores usados pelo Alembic para encadear as migrações.
revision: str = '24ab6255ddc0'
down_revision: str | Sequence[str] | None = '5ef5fda8e15a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('de', sa.String(length=30), nullable=True),
    sa.Column('para', sa.String(length=30), nullable=False),
    sa.Column('por_quem', sa.String(length=100), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('em', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_status_insight_id'), ['insight_id'], unique=False)

    op.create_table('relacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('relacionado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('insight_id <> relacionado_id', name='ck_relacoes_nao_aponta_para_si'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['relacionado_id'], ['insights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insight_id', 'relacionado_id', 'tipo', name='uq_relacoes_par_tipo')
    )
    with op.batch_alter_table('relacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relacoes_insight_id'), ['insight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relacoes_relacionado_id'), ['relacionado_id'], unique=False)

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index('ix_insights_secao_segmento', ['secao', 'segmento'], unique=False)
        batch_op.create_index('ix_insights_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_status')
        batch_op.drop_index('ix_insights_secao_segmento')

    with op.batch_alter_table('relacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relacoes_relacionado_id'))
        batch_op.drop_index(batch_op.f('ix_relacoes_insight_id'))

    op.drop_table('relacoes')
    with op.batch_alter_table('historico_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_status_insight_id'))

    op.drop_table('historico_status')
    # ### end Alembic commands ###
